# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SamApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SamApp
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'SwiftyJSON'
  pod 'MBRadioButton'
  pod 'FontAwesomeKit'
  pod 'SVProgressHUD'
#  pod 'GoogleAnalytics'
  pod 'hkAlium'
  pod 'DLRadioButton', '~> 1.4'
  pod 'SKPhotoBrowser'
  pod 'SDWebImage', '~> 5.0'
  pod 'Firebase/Crashlytics'

  target 'SamAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SamAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

 post_install do |installer|
    xcode_base_version = `xcodebuild -version | grep 'Xcode' | awk '{print $2}' | cut -d . -f 1`

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # For xcode 15+ only
             if config.base_configuration_reference && Integer(xcode_base_version) >= 15
                xcconfig_path = config.base_configuration_reference.real_path
                xcconfig = File.read(xcconfig_path)
                xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
                File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
            end
        end
    end
end
